# Generated by Django 5.0.9 on 2024-12-24 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rchpackage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['-uploaded_at']},
        ),
    ]
