# Generated by Django 5.0.14 on 2025-06-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], max_length=10)),
                ('birthday', models.DateTimeField()),
                ('phonenumber', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'auth_account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Aumper',
            fields=[
                ('AumperCode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('AumperDesc', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Aumper',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatientData',
            fields=[
                ('citizenID', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('titlename', models.CharField(blank=True, max_length=50, null=True)),
                ('addressNo', models.CharField(blank=True, max_length=10, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('moo', models.CharField(blank=True, max_length=10, null=True)),
                ('zipCode', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'PatientData',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('ProvinceCode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ProvinceDesc', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Province',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tambol',
            fields=[
                ('TambolCode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TambolDesc', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Tambol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=15, null=True)),
                ('first_name', models.CharField(blank=True, max_length=15, null=True)),
                ('last_name', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'Auth User',
                'verbose_name_plural': 'Auth User',
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
    ]
