# Generated by Django 5.0.9 on 2025-02-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aumper',
            fields=[
                ('AumperCode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('AumperDesc', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Aumper',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenID', models.CharField(max_length=20, unique=True)),
                ('titlename', models.CharField(blank=True, max_length=50, null=True)),
                ('addressNo', models.CharField(blank=True, max_length=10, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('moo', models.CharField(blank=True, max_length=10, null=True)),
                ('zipCode', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'PatientData',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('ProvinceCode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ProvinceDesc', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Province',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tambol',
            fields=[
                ('TambolCode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TambolDesc', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Tambol',
                'managed': False,
            },
        ),
    ]
