# Generated by Django 5.0.14 on 2025-06-13 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table=None,
        ),
    ]
