# Generated by Django 5.0.14 on 2025-06-17 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rcheven', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'managed': False},
        ),
    ]
