# Generated by Django 5.0.14 on 2025-06-17 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rcheven', '0002_alter_event_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table='ScheduleDoctor',
        ),
    ]
