# Generated by Django 5.0.9 on 2025-02-05 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rcharticle', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-uploaded_at']},
        ),
    ]
